name: GitHub Actions Demo
on:
  pull_request:
    paths: 'main/**'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Release APK
        run: ./gradlew assembleRelease
