name: GitHub Actions Demo
on:
  push:
    branches: main

jobs:
  CI-CD:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Get app version
        run: |
          $TimestampEpoch = Get-Date -Date '2021-01-01'
          $DaysSinceEpoch = (New-TimeSpan -Start $TimestampEpoch -End $(Get-Date)).Days
          $MinutesSinceMidnight= [int] (New-TimeSpan -Start $(Get-Date -Hour 0 -Minute 00 -Second 00) -End $(Get-Date)).TotalMinutes
          $MinutesSinceMidnightFourDigits = ([string]$minutesSinceMidnight).PadLeft(4,'0')
          $AppVersionNumericSeparatedByDots = "0.$DaysSinceEpoch.$MinutesSinceMidnight"
          $AppVersionStringOverlappedAndPadded = "0$DaysSinceEpoch$MinutesSinceMidnightFourDigits"
          # Set output variables
          Write-Host "App version -> $AppVersionNumericSeparatedByDots, setting output variable 'appversion'"
          Write-Host "##vso[task.setvariable variable=appversion;isOutput=true]$AppVersionNumericSeparatedByDots"
          Write-Host "String app version -> $AppVersionStringOverlappedAndPadded, setting output variable 'stringappversion'"
          Write-Host "##vso[task.setvariable variable=stringappversion;isOutput=true]$AppVersionStringOverlappedAndPadded"
          # Update build name
          Write-Host "##vso[build.updatebuildnumber]$AppVersionNumericSeparatedByDots"
        shell: pwsh

    - name: Build Release APK
      run: ./gradlew assembleRelease
